mode = "dark"
accent = "#268bd2"
selection = "#073642"
muted = "#586e75"
background = "#002b36"
dark_background = "#001e26"
darker_background = "#00141a"
lighter_background = "#073642"
foreground = "#839496"
dark_foreground = "#586e75"
light_foreground = "#93a1a1"
bright_foreground = "#eee8d5"
red = "#dc322f"
yellow = "#b58900"
orange = "#cb4b16"
green = "#859900"
cyan = "#2aa198"
blue = "#268bd2"
magenta = "#d33682"
brown = "#8a5a44"
bright_red = "#cb4b16"
bright_yellow = "#657b83"
bright_green = "#586e75"
bright_cyan = "#93a1a1"
bright_blue = "#839496"
bright_magenta = "#6c71c4"
