{ ... }:
{
  # AUTO-GENERATED by `omanix state set` — do not edit by hand.
  # Machine-produced option values. configuration.nix imports this file, so the
  # values reach `omanix rebuild` through the normal module system.
}