{ ... }:
{
  # AUTO-GENERATED by `omanix state set` — do not edit by hand.
  #
  # This file holds machine-produced option values (written by the Omanix GUI and CLI).
  # It is the SINGLE writer target for declarative settings — the GUI never hand-edits
  # configuration.nix. Human-authored choices stay in configuration.nix; everything the
  # app toggles lands here as a strict, validated Nix module.
  #
  # Example entries (generated automatically):
  #   omanix.omabar.showClock = true;
  #   omanix.omatiles.enableKeyboardShortcuts = true;
}
