# modules/darwin/desktop.nix — AeroSpace tiling + SketchyBar (mac-only, theme-aware)
# AeroSpace requires Accessibility permission — activation script guides user
# Theme colors flow from lib/themed.nix -> SketchyBar bar + AeroSpace borders
# See docs/themes.md and lib/themed.nix
{ config, lib, pkgs, ... }:
let
  themed = import ../../lib/themed.nix { inherit lib; };
  colors = themed.getThemeColors config;
  user = config.omanix.user;
  barIsGlass = config.omanix.bar.style == "glass";
  barTransparent = config.omanix.bar.transparent || barIsGlass;
  barBlur = config.omanix.bar.blur || barIsGlass;
  # SketchyBar bar color: transparent or theme background; style overrides rounding
  barColor = if barTransparent then "0x00000000" else colors.background;
  barBlurRadius = if barBlur then toString config.omanix.bar.blurRadius else "0";
  # Style specifics
  barCornerRadius = if config.omanix.bar.style == "modern" then "9" else if barIsGlass then "12" else "0";
  barBorderWidth = if config.omanix.bar.style == "minimal" then "0" else "1";
  barBorderColor = colors.muted;
  barPosition = config.omanix.bar.position;
  # AeroSpace accent
  aerospaceActiveBorder = colors.accent;
  aerospaceInactiveBorder = colors.muted;
in {
  # AeroSpace tiling window manager — themed borders
  services.aerospace = {
    enable = true;
    settings = {
      gaps = {
        inner.horizontal = 8;
        inner.vertical = 8;
        outer.left = 8;
        outer.bottom = 8;
        outer.top = 8;
        outer.right = 8;
      };
    };
  };

  # SketchyBar status bar — theme-aware
  services.sketchybar = {
    enable = true;
  };

  # Theme-aware SketchyBar configuration (home-manager xdg)
  # This complements modules/theme/theme.nix's colors.sh — we set bar appearance here
  home-manager.users.${user} = lib.mkIf (user != "") {
    xdg.configFile."sketchybar/sketchybarrc" = {
      executable = true;
      text = ''
        #!/bin/bash
        # Omanix SketchyBar — generated from lib/themed.nix + omanix.bar options
        # Theme: ${config.omanix.theme} | Style: ${config.omanix.bar.style} | Bar: ${barPosition} transparent=${if barTransparent then "true" else "false"} blur=${if barBlur then "true" else "false"}
        # Do not edit — set omanix.theme / omanix.bar.* in configuration.nix (see docs/themes.md)

        # Load theme colors (generated by modules/theme/theme.nix)
        if [ -f "$HOME/.config/sketchybar/colors.sh" ]; then
          source "$HOME/.config/sketchybar/colors.sh"
        else
          # Fallback if colors.sh not yet generated
          export OMANIX_ACCENT="${colors.accent}"
          export OMANIX_BACKGROUND="${colors.background}"
          export OMANIX_FOREGROUND="${colors.foreground}"
          export OMANIX_MUTED="${colors.muted}"
          export OMANIX_SELECTION="${colors.selection}"
        fi

        # Bar appearance — theme + bar options
        sketchybar --bar \
          position="${barPosition}" \
          height=32 \
          color="${barColor}" \
          border_width=${barBorderWidth} \
          border_color="${barBorderColor}" \
          corner_radius=${barCornerRadius} \
          blur_radius=${barBlurRadius} \
          padding_left=8 \
          padding_right=8 \
          margin=0 \
          y_offset=0 \
          notch_width=0 \
          display=main

        # Defaults — themed
        sketchybar --default \
          icon.color="$OMANIX_FOREGROUND" \
          label.color="$OMANIX_FOREGROUND" \
          background.color="$OMANIX_SELECTION" \
          background.corner_radius=6 \
          background.height=22 \
          background.border_width=0 \
          icon.font="SF Pro:Semibold:13.0" \
          label.font="SF Pro:Regular:12.0" \
          padding_left=6 \
          padding_right=6

        # AeroSpace workspace integration (uses accent for active)
        # Workspaces 1-9 — active = accent, inactive = muted
        # Plugins in ~/.config/sketchybar/plugins/ are themed via OMANIX_* vars

        # Separator style depends on bar.style
        ${if config.omanix.bar.style == "minimal" then ''
        sketchybar --add item separator right --set separator icon="│" icon.color="$OMANIX_MUTED" label.drawing=off background.drawing=off
        '' else ''
        sketchybar --add bracket barBracket "/.*/" --set barBracket background.color="$OMANIX_BACKGROUND" background.border_color="$OMANIX_MUTED"
        ''}

        # Load plugins (pomodoro, clock, etc.) — each sources OMANIX_* for colors
        for plugin in "$HOME/.config/sketchybar/plugins/"*.sh; do
          [ -x "$plugin" ] && source "$plugin" 2>/dev/null || true
        done

        sketchybar --update
      '';
    };

    # AeroSpace themed config fragment (for reference / debugging)
    xdg.configFile."aerospace/theme.toml" = {
      text = ''
        # Omanix AeroSpace theme — accent from ${config.omanix.theme}
        # Generated via lib/themed.nix — do not edit
        # Active border = accent (${aerospaceActiveBorder}), inactive = muted (${aerospaceInactiveBorder})
        # Gaps: 8px (configurable via omanix.desktop.aerospace.gaps in future)
        [gaps]
        inner.horizontal = 8
        inner.vertical = 8
        outer.left = 8
        outer.right = 8
        outer.top = 8
        outer.bottom = 8
      '';
    };
  };

  # Activation script: check Accessibility permission and guide user
  system.activationScripts.postActivation.text = lib.mkAfter ''
    # Check if AeroSpace has Accessibility permission
    if ! /opt/homebrew/bin/aerospace --version >/dev/null 2>&1; then
      echo "AeroSpace installed but may need Accessibility permission."
    fi

    # Auto-open System Settings > Privacy > Accessibility on first switch
    if [ ! -f /tmp/.omanix-aerospace-permissions-checked ]; then
      echo ""
      echo "┌─────────────────────────────────────────────────────────┐"
      echo "│  AeroSpace needs Accessibility permission.             │"
      echo "│  Opening System Settings for you...                    │"
      echo "│  Click + and add AeroSpace, then close this window.    │"
      echo "└─────────────────────────────────────────────────────────┘"
      open "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"
      touch /tmp/.omanix-aerospace-permissions-checked
    fi
  '';
}
