mode = "dark"
accent = "#7e9cd8"
selection = "#2d4f67"
muted = "#727169"
background = "#1f1f28"
dark_background = "#16161d"
darker_background = "#0a0a12"
lighter_background = "#2a2a37"
foreground = "#dcd7ba"
dark_foreground = "#938aa9"
light_foreground = "#e8e0c8"
bright_foreground = "#dcd7ba"
red = "#c34043"
yellow = "#c0a36e"
orange = "#ffa066"
green = "#76946a"
cyan = "#6a9589"
blue = "#7e9cd8"
magenta = "#957fb8"
brown = "#7e5e4a"
bright_red = "#e82424"
bright_yellow = "#e6c384"
bright_green = "#98bb6c"
bright_cyan = "#7aa89f"
bright_blue = "#7fb4ca"
bright_magenta = "#a292a3"
