mode = "dark"
accent = "#ebbcba"
selection = "#26233a"
muted = "#6e6a86"
background = "#191724"
dark_background = "#12111a"
darker_background = "#0e0d12"
lighter_background = "#1f1d2e"
foreground = "#e0def4"
dark_foreground = "#908caa"
light_foreground = "#e0def4"
bright_foreground = "#e0def4"
red = "#eb6f92"
yellow = "#f6c177"
orange = "#ebbcba"
green = "#31748f"
cyan = "#9ccfd8"
blue = "#31748f"
magenta = "#c4a7e7"
brown = "#7e5a4a"
bright_red = "#eb6f92"
bright_yellow = "#f6c177"
bright_green = "#9ccfd8"
bright_cyan = "#9ccfd8"
bright_blue = "#31748f"
bright_magenta = "#c4a7e7"
