#!/bin/bash
# libexec/omanix-state.sh — declarative state mutator for Omanix.
#
# The ONLY sanctioned way for the Omanix GUI/CLI to change declarative options.
# It writes to the generated `state.nix` (never configuration.nix), validating the
# option key and the value's type against this script's schema. configuration.nix
# imports state.nix, so `omanix rebuild` picks the value up through the normal module
# system — the GUI never performs free-form Nix text surgery on the source of truth.
#
# Usage:
#   omanix state set <option.path> <value>   Write a validated option (bool/string/int)
#   omanix state get <option.path>           Print current value (or "unset")
#   omanix state list                        List known options + current values
#   omanix state reset                       Empty state.nix back to defaults
#   omanix state ensure                      Create state.nix if missing (machine-owned, gitignored)
#   omanix state prune                       Drop stale option paths, if any forgot to disappear
set -euo pipefail

FLAKE_DIR="${FLAKE_DIR:-$HOME/.omanix}"
STATE_FILE="$FLAKE_DIR/state.nix"

# --- Schema: option path -> nix primitive type -------------------------------
# Keep in sync with the lib.mkOption declarations in modules/*/options.nix.
schema() {
  case "$1" in
    omanix.omatiles.enable|omanix.omatiles.bindings|omanix.omatiles.enableEdgeDrag|omanix.omatiles.enableKeyboardShortcuts|omanix.omatiles.enableMargins) echo bool ;;
    omanix.widgets.gui.enable|omanix.widgets.store.enable|omanix.widgets.pomodoro.enable|omanix.widgets.clock.enable) echo bool ;;
    omanix.theme) echo string ;;
    *) echo "" ;;
  esac
}

# --- value -> Nix literal -----------------------------------------------------
to_literal() {
  local type="$1" value="$2" esc
  case "$type" in
    bool)
      case "$value" in
        true|false) echo "$value" ;;
        *) echo "ERROR: expected true|false for bool option" >&2; return 1 ;;
      esac ;;
    string)
      # Bare `null` maps to a Nix null literal (nullable string options).
      if [[ "$value" == "null" ]]; then
        echo "null"; return 0
      fi
      esc="${value//\\/\\\\}"
      esc="${esc//\"/\\\"}"
      echo "\"$esc\"" ;;
    int)
      if [[ "$value" =~ ^[0-9]+$ ]]; then
        echo "$value"
      else
        echo "ERROR: expected a positive integer for int option" >&2; return 1
      fi ;;
    *) echo "ERROR: unknown option type '$type'" >&2; return 1 ;;
  esac
}

# Is an existing Nix literal well-formed for its type? Used to drop corrupt
# leftovers (e.g. an unterminated string) when regenerating state.nix.
literal_ok() {
  local type="$1" lit="$2"
  case "$type" in
    bool)
      [[ "$lit" == "true" || "$lit" == "false" ]] ;;
    string)
      [[ "$lit" == "null" || ( "$lit" =~ ^\".*\"$ ) ]] ;;
    int)
      [[ "$lit" =~ ^[0-9]+$ ]] ;;
    *) return 1 ;;
  esac
}

# --- state.nix IO --------------------------------------------------------------
# Read existing entries from state.nix as lines: `path<TAB>literal`.
read_entries() {
  grep -E '^[[:space:]]+omanix\.[a-zA-Z0-9._]+ = ' "$STATE_FILE" 2>/dev/null \
    | sed -E 's/^[[:space:]]+(omanix\.[a-zA-Z0-9._]+) = (.*);$/\1\t\2/' || true
}

# Regenerate state.nix from a set of `path<TAB>literal` lines (already stable-ordered).
write_state() {
  local entries="$1" tmp k v
  tmp="$(mktemp "$FLAKE_DIR/state.nix.XXXXXX")"
  {
    printf '{ ... }:\n{\n'
    printf '  # AUTO-GENERATED by `omanix state set` — do not edit by hand.\n'
    printf '  # Machine-produced option values. configuration.nix imports this file, so the\n'
    printf '  # values reach `omanix rebuild` through the normal module system.\n'
    while IFS=$'\t' read -r k v; do
      [[ -n "$k" ]] && printf '  %s = %s;\n' "$k" "$v"
    done < "$entries"
    printf '}\n'
  } > "$tmp"
  mv "$tmp" "$STATE_FILE"
  chmod 0644 "$STATE_FILE"
}

# --- Commands ------------------------------------------------------------------
set_option() {
  local path="${1:-}" value="${2:-}"
  if [[ -z "$path" || -z "$value" ]]; then
    echo "Usage: omanix state set <option.path> <value>" >&2
    exit 1
  fi
  local type literal
  type="$(schema "$path")"
  [[ -z "$type" ]] && { echo "ERROR: unknown option '$path'. Run 'omanix state list'." >&2; exit 1; }
  literal="$(to_literal "$type" "$value")" || exit 1

  # Build an updated entries list (known paths preserved, target updated/added;
  # stale paths dropped so one set also heals state.nix after option renames).
  local entries updated found=0
  entries="$(read_entries)"
  updated="$(mktemp)"
  while IFS=$'\t' read -r p l; do
    if [[ "$p" == "$path" ]]; then
      printf '%s\t%s\n' "$path" "$literal"; found=1
    elif [[ -n "$p" ]] && [[ -n "$(schema "$p")" ]] && literal_ok "$(schema "$p")" "$l"; then
      printf '%s\t%s\n' "$p" "$l"
    fi
  done <<< "$entries" > "$updated"
  if [[ "$found" == "0" ]]; then
    printf '%s\t%s\n' "$path" "$literal" >> "$updated"
  fi
  # Stable order by path so diffs stay minimal and readable.
  sort -t$'\t' -k1,1 "$updated" -o "$updated"
  write_state "$updated"
  rm -f "$updated"
  echo "state: $path = $literal"
  echo "Run 'omanix rebuild' to apply."
}

get_option() {
  local path="${1:-}"
  [[ -z "$path" ]] && { echo "Usage: omanix state get <option.path>" >&2; exit 1; }
  local type
  type="$(schema "$path")" || true
  if [[ -z "$type" ]]; then echo "ERROR: unknown option '$path'" >&2; exit 1; fi
  local found=""
  while IFS=$'\t' read -r p l; do
    [[ "$p" == "$path" ]] && { found="$l"; break; }
  done <<< "$(read_entries)"
  if [[ -n "$found" ]]; then
    echo "$found"
  else
    echo "unset"
  fi
}

list_options() {
  local path v
  printf '%-45s %-16s %s\n' "OPTION" "TYPE" "CURRENT"
  for path in omanix.omatiles.enable omanix.omatiles.bindings omanix.omatiles.enableEdgeDrag omanix.omatiles.enableKeyboardShortcuts omanix.omatiles.enableMargins \
               omanix.widgets.gui.enable omanix.widgets.store.enable omanix.widgets.pomodoro.enable omanix.widgets.clock.enable \
               omanix.theme; do
    v="$(get_option "$path")"
    printf '%-45s %-16s %s\n' "$path" "$(schema "$path")" "$v"
  done
}

reset_state() {
  write_state <(printf '')
  echo "state.nix reset to defaults."
}

# Create state.nix from the default template if missing. state.nix is a
# machine-owned, gitignored file — never tracked/committed.
ensure_state_file() {
  if [[ ! -f "$STATE_FILE" ]]; then
    write_state <(printf '')
    echo "state: created $STATE_FILE"
  fi
}

# Drop any entry whose option path is not in the schema. After an upgrade that
# renames/removes options (e.g. omabar -> spacebar), stale keys would otherwise
# fail the rebuild with "option `x' does not exist".
prune_state() {
  local clean
  clean="$(mktemp)"
  while IFS=$'\t' read -r p l; do
    if [[ -n "$p" ]] && [[ -n "$(schema "$p")" ]] && literal_ok "$(schema "$p")" "$l"; then
      printf '%s\t%s\n' "$p" "$l"
    fi
  done <<< "$(read_entries)" > "$clean"
  sort -t$'\t' -k1,1 "$clean" -o "$clean"
  write_state "$clean"
  rm -f "$clean"
  echo "state: pruned to schema-known options."
}

# --- Live apply ---------------------------------------------------------------
# Applies the resolved declarative state to the running system NOW, without waiting for
# a rebuild. This is the Nix-owned live-apply path: the actual OS mutation (macro
# defaults writes, service restarts) mirrors what the activation scripts do, so all
# mutation logic lives here + in the nix modules — never scattered in the GUI.
apply_area() {
  local area="${1:-}"
  case "$area" in
    omatiles)
      apply_omatiles
      ;;
    *)
      echo "Usage: omanix state apply <omatiles>" >&2
      exit 1 ;;
  esac
}

apply_omatiles() {
  local edgeDrag accelerator margins
  edgeDrag="$(get_option omanix.omatiles.enableEdgeDrag)"
  accelerator="$(get_option omanix.omatiles.enableKeyboardShortcuts)"
  margins="$(get_option omanix.omatiles.enableMargins)"
  # Resolve against the same defaults as modules/theme/options.nix.
  [[ "$edgeDrag" == "unset" ]] && edgeDrag=true
  [[ "$accelerator" == "unset" ]] && accelerator=true
  [[ "$margins" == "unset" ]] && margins=false

  if [[ "$OSTYPE" == "darwin"* ]]; then
    defaults write com.apple.WindowManager EnableTilingByEdgeDrag -bool "$edgeDrag" 2>/dev/null || true
    defaults write com.apple.WindowManager EnableTilingWithAccelerator -bool "$accelerator" 2>/dev/null || true
    defaults write com.apple.WindowManager EnableTiledWindowMargins -bool "$margins" 2>/dev/null || true
    killall WindowManager 2>/dev/null || true
    echo "omatiles: applied macOS tiling prefs (edgeDrag=$edgeDrag accelerator=$accelerator margins=$margins)"
  else
    echo "omatiles: no live apply on $OSTYPE yet (declarative only)" >&2
  fi
}

# --- dispatch ------------------------------------------------------------------
case "${1:-help}" in
  set)   set_option "${2:-}" "${3:-}" ;;
  get)   get_option "${2:-}" ;;
  list)  list_options ;;
  reset) reset_state ;;
  ensure) ensure_state_file ;;
  prune) prune_state ;;
  apply) apply_area "${2:-}" ;;
  help|--help|-h|"")
    cat <<'EOF'
Usage: omanix state <subcommand> [args]
  set <option.path> <value>   Write a validated option (bool/string/int). Then run `omanix rebuild`.
  get <option.path>           Print the current value ("unset" if not set).
  list                        List known options, types, and current values.
  apply <area>                Apply resolved declarative state to the live system NOW
                              (currently supported: omatiles). No rebuild needed.
  reset                       Empty state.nix back to defaults.
  ensure                      Create state.nix from the default template if missing.
  prune                       Drop stale option paths that no longer exist in the schema.
EOF
    ;;
  *) echo "Unknown state subcommand: $1" >&2; exit 1 ;;
esac
