mode = "dark"
accent = "#bd93f9"
selection = "#44475a"
muted = "#6272a4"
background = "#282a36"
dark_background = "#1e1f29"
darker_background = "#12131a"
lighter_background = "#343746"
foreground = "#f8f8f2"
dark_foreground = "#6272a4"
light_foreground = "#f8f8f2"
bright_foreground = "#ffffff"
red = "#ff5555"
yellow = "#f1fa8c"
orange = "#ffb86c"
green = "#50fa7b"
cyan = "#8be9fd"
blue = "#bd93f9"
magenta = "#ff79c6"
brown = "#8a6a4a"
bright_red = "#ff5555"
bright_yellow = "#f1fa8c"
bright_green = "#50fa7b"
bright_cyan = "#8be9fd"
bright_blue = "#bd93f9"
bright_magenta = "#ff79c6"
