mode = "dark"
accent = "#88c0d0"
selection = "#434c5e"
muted = "#4c566a"
background = "#2e3440"
dark_background = "#242933"
darker_background = "#1a1e26"
lighter_background = "#3b4252"
foreground = "#eceff4"
dark_foreground = "#d8dee9"
light_foreground = "#eceff4"
bright_foreground = "#eceff4"
red = "#bf616a"
yellow = "#ebcb8b"
orange = "#d08770"
green = "#a3be8c"
cyan = "#8fbcbb"
blue = "#81a1c1"
magenta = "#b48ead"
brown = "#7b6a5a"
bright_red = "#bf616a"
bright_yellow = "#ebcb8b"
bright_green = "#a3be8c"
bright_cyan = "#88c0d0"
bright_blue = "#81a1c1"
bright_magenta = "#b48ead"
