mode = "dark"
accent = "#fab795"
selection = "#2e303e"
muted = "#6c6f93"
background = "#1c1e26"
dark_background = "#16161e"
darker_background = "#0f0f14"
lighter_background = "#2a2c38"
foreground = "#cbced0"
dark_foreground = "#6c6f93"
light_foreground = "#e0e2e5"
bright_foreground = "#ffffff"
red = "#e95678"
yellow = "#fab795"
orange = "#f09383"
green = "#29d398"
cyan = "#59e1e3"
blue = "#26bbd9"
magenta = "#b877db"
brown = "#8a6a5a"
bright_red = "#ec6a88"
bright_yellow = "#efb993"
bright_green = "#3fdaa4"
bright_cyan = "#59e1e3"
bright_blue = "#26bbd9"
bright_magenta = "#b877db"
